[WIP] Add home page
crux-bphc/chronofactorem-rewrite pull request #114
Opened 2023-12-29 17:33 UTC by pnicto

closes #104

Things that need further input:
- [ ] To `useMemo` or not to. (Will require some refactoring to use the hook on the filter function)

2023-12-30 09:29 UTC, soumitradev requested changes
Few changes mostly related to styling of the page

2023-12-30 09:29 UTC, soumitradev commented on frontend/src/Home.tsx
> +            )}
Here I'd say a few things:
- Show Draft timetables at the top, since we want to emphasize on finishing them first, since the current use case is more focused on making timetables and not as much on sharing them. Private and public you can show in any order that makes sense to you after that.
- If there are no timetables to show in a particular heading then just don't render the heading
- If there are no timetables to show in any of the headings then don't render anything, and instead render a prompt to create a timetable like the current frontend does

2023-12-30 09:29 UTC, soumitradev commented on frontend/src/Home.tsx
> +        <main className="bg-primary min-h-screen text-primary-foreground px-8 py-20 md:px-20 lg:px-20 xl:px-48">
I think the padding-x is too much here in the case of all screens; it should just be a small amount of padding

2023-12-30 09:29 UTC, soumitradev commented on frontend/src/components/TimetableCard.tsx
> +        </Button>
imo make these icons slighly smaller in general for all devices

2023-12-30 09:29 UTC, soumitradev commented on frontend/src/Home.tsx
> +        <div className="grid gap-8 grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 pt-4">
imo instead of varying the grid columns, just make a flex container and dump them there with flex-wrap, I feel like that looks better than the variable gap on different devices of different sizes. e.g. The gap on large devices is way too much rn, but the gap on medium to small devices is fine although still on the higher side

tl;dr: reduce gap in general a little bit from 8, and then consider changing this to a flex with flex-wrap instead. Make sure you consult with people on discord if that would look better or not.

2023-12-30 09:29 UTC, soumitradev commented on frontend/src/components/TimetableCard.tsx
> +        </Button>
also if possible make the icon buttons completely round

2023-12-30 09:29 UTC, soumitradev commented on frontend/src/components/TimetableCard.tsx
> +    <Card className="min-w-fit max-w-sm min-h-60 flex flex-col">
also this card as of now lacks any kind of hover feedback so fix that too ig

2023-12-30 12:09 UTC, pnicto commented on frontend/src/components/TimetableCard.tsx
> +        </Button>
I tried making them smaller and I don't like it if others also say the same I will make them smaller.

2023-12-30 12:18 UTC, pnicto commented on frontend/src/components/TimetableCard.tsx
> +    <Card className="min-w-fit max-w-sm min-h-60 flex flex-col">
one day, when the card colors make their debut

2023-12-30 13:28 UTC, soumitradev requested changes
more style related changes

2023-12-30 13:28 UTC, soumitradev commented on frontend/src/Home.tsx
> +          ) : (
this part is now redundant, you can edit the condition on line 59 to be `<=` too.

2023-12-30 13:28 UTC, soumitradev commented on frontend/src/components/TimetableCard.tsx
> +          onClick={() => deleteMutation.mutate()}
here this should probably display a confirmation modal or something before directly calling the API

2023-12-30 13:28 UTC, soumitradev commented on frontend/src/components/TimetableCard.tsx
> +              isPrivate: timetable.private,
this fails for public timetables, isPrivate should always be false here

2023-12-30 13:28 UTC, soumitradev commented on frontend/src/components/TimetableCard.tsx
> +            onClick={() =>
This should also probably show a confirmation modal but maybe confirm with others if they think the same, I'm not fully convinced if it should either

2023-12-30 13:28 UTC, soumitradev commented on frontend/src/components/TimetableCard.tsx
> +    <Card className="min-h-60 flex flex-col min-w-80 shadow-lg">
probably reduce the min width on smaller devices cuz on some of the phone models the cards are either not centred or are overflowing

2023-12-30 13:28 UTC, soumitradev commented on frontend/src/components/TimetableCard.tsx
> +          className="rounded-full p-3"
here this should probably have `hover:bg-destructive/90 hover:text-destructive-foreground` as it's a destructive action, but don't make the entire button destructive cuz that looks ugly

2023-12-30 13:28 UTC, soumitradev commented on frontend/src/Home.tsx
> +                <div className="bg-secondary mt-10 text-center flex flex-col items-center justify-center gap-8 py-16 rounded-lg">
here probably a good idea to scale the text and icon according to the device size, it looks too big on phones

2023-12-30 13:28 UTC, soumitradev commented on frontend/src/Home.tsx
> +          <h1 className="text-5xl font-bold text-center sm:text-left">
here the text starts wrapping on phones and it takes up unnecessary vertical space, probably a good idea to reduce the text size on smaller devices

2024-01-01 10:37 UTC, soumitradev requested changes
One last change before we can merge

2024-01-01 10:37 UTC, soumitradev commented on frontend/src/Home.tsx
> +        <main className="bg-background min-h-screen text-foreground py-20 px-10 md:px-16">
```suggestion
        <main className="text-foreground py-6 md:py-12 px-10 md:px-16">
```
Since the navbar is now rendering on this page, the spacing here can be reduced, and since the background will anyways be `bg-background`, the `h-screen` stuff is no longer needed.

2024-01-01 10:40 UTC, soumitradev commented
Nevermind, archived timetables are still remaining

2024-01-01 10:51 UTC, soumitradev commented
So a couple more things:
- Clicking the create timetable button shouldn't just create the timetable, it should also navigate you to that timetable's edit page directly. As this is only a small change, you can choose to implement this right now or make an issue and leave it for a future PR when the edit timetable page is ready.
- I'm not entirely sure if it makes sense to have an edit button separately on a draft timetable, as the default click behavior should take you to the editor. I can see why an edit button can make this default click action more intuitive, however. So I'd say this is not that important but it is best to discuss before we release. You can choose to make an issue for this as well.
- Archived timetables can be deleted, and their name, and visibility can be edited. You cannot make an archived timetable draft, however. Since archived timetables will probably show up at the bottom of the page, and the visibility of archived timetables isn't a priority for this release, you can choose whether you want to implement this feature or create an issue that we can resolve in some future release.
  - Ideally, I'd say the edit behaviour for archived timetables should be such that on pressing the edit button you get a modal where you can edit the name, and toggle the visibility of the timetable between public and private.
  - The delete behaviour for archived timetables would be the exact same as for any other timetable.

2024-01-01 14:32 UTC, pnicto commented
> So a couple more things:
> 
> * Clicking the create timetable button shouldn't just create the timetable, it should also navigate you to that timetable's edit page directly. As this is only a small change, you can choose to implement this right now or make an issue and leave it for a future PR when the edit timetable page is ready.
> * I'm not entirely sure if it makes sense to have an edit button separately on a draft timetable, as the default click behavior should take you to the editor. I can see why an edit button can make this default click action more intuitive, however. So I'd say this is not that important but it is best to discuss before we release. You can choose to make an issue for this as well.
> * Archived timetables can be deleted, and their name, and visibility can be edited. You cannot make an archived timetable draft, however. Since archived timetables will probably show up at the bottom of the page, and the visibility of archived timetables isn't a priority for this release, you can choose whether you want to implement this feature or create an issue that we can resolve in some future release.
>   
>   * Ideally, I'd say the edit behaviour for archived timetables should be such that on pressing the edit button you get a modal where you can edit the name, and toggle the visibility of the timetable between public and private.
>   * The delete behaviour for archived timetables would be the exact same as for any other timetable.

For the 2nd one, I have asked the chat for their opinion as this is a small change. If nothing conclusive comes out then I will make an issue.

2024-01-01 14:41 UTC, pnicto commented on frontend/src/components/TimetableCard.tsx
> +    <Card className="min-w-fit max-w-sm min-h-60 flex flex-col">
Made an issue for this #132 and I will mark this as resolved.

2024-01-01 16:08 UTC, soumitradev requested changes
One last thing: can you include an icon for public/rpivate timetables when they are archived? It's not exactly clear since they live right next to each other under the subheading.

2024-01-01 16:38 UTC, soumitradev approved these changes
LGTM

2024-01-01 16:39 UTC, merged