Add edit user page
crux-bphc/chronofactorem-rewrite pull request #117
Opened 2023-12-30 11:11 UTC by JustAGhost23

Added the edit user page, might need a few changes.

2023-12-30 16:35 UTC, soumitradev requested changes
Some logic and error handling related changes. Still need to standardize colors after this again, so don't merge.

2023-12-30 16:35 UTC, soumitradev commented on frontend/src/EditUserProfile.tsx
> +          <div className="rounded-full text-slate-50 bg-slate-500 lg:px-9 lg:py-6 lg:text-6xl px-7 py-4 text-4xl lg:h-28 lg:w-28 h-20 w-20 lg:mx-4 mx-2 lg:mt-4 lg:mb-8 mt-2 mt-4">
I agree this is brain damage, and instead, you can use a flexbox, it makes life much easier:
```suggestion
          <div className="rounded-full text-slate-50 bg-slate-500 lg:text-6xl text-4xl lg:h-28 lg:w-28 h-20 w-20 flex justify-center items-center">
```

2023-12-30 16:35 UTC, soumitradev commented on frontend/src/EditUserProfile.tsx
> +            <span>{userQueryResult.data.name[0]}</span>
All instances of `userQueryResult.data.*` are invalid here, since `userQueryResult.data` can be undefined according to the type. So, around line 201, you can add an if statement checking if `userQueryResult.data` is undefined, and if it is, you can return some kind of error similar to:

```tsx
  if (userQueryResult.data === undefined) {
    return (
      <span>
        Unexpected error: userQueryResult.data is undefined. Please
        report this{" "}
        <a href="https://github.com/crux-bphc/chronofactorem-rewrite/issues">
          here
        </a>
      </span>
    );
  }

  return (
    <>
    // rest of your component
  ```

2023-12-30 16:35 UTC, soumitradev commented on frontend/src/EditUserProfile.tsx
> +              <Select onValueChange={setSecondDegree}>
```suggestion
            {firstDegree.includes("B") && (
              <Select
                onValueChange={setSecondDegree}
                value={secondDegree ?? undefined}
              >
```

Here if you change the internal value logic to accommodate for both cases, the next `<Select>` becomes redundant and can be removed.

2023-12-30 16:35 UTC, soumitradev commented on frontend/src/EditUserProfile.tsx
> +            )}
```suggestion

```

Based on my previous suggestion you can remove this whole select block

2023-12-30 16:35 UTC, soumitradev commented on frontend/src/EditUserProfile.tsx
> +          <div className="flex lg:flex-row flex-col">
Medium and small screens like tablets can handle this page just fine, so instead of `lg:flex-row` you can use `sm:flex-row` instead, but this means you will have to also adjust the x-margin on the next Select

2023-12-30 16:35 UTC, soumitradev commented on frontend/src/EditUserProfile.tsx
> +                <SelectTrigger className="w-84 lg:mx-4 bg-slate-800 border-slate-700 focus:ring-slate-800 focus:ring-offset-slate-800 text-slate-50 mt-2">
Based on my previous suggestion about screen sizes, you will have to edit the x-margin to show up on small and medium screens as well.
```suggestion
                <SelectTrigger className="w-84 sm:mx-4 bg-slate-800 border-slate-700 focus:ring-slate-800 focus:ring-offset-slate-800 text-slate-50 mt-2">
```

2023-12-30 16:35 UTC, soumitradev commented on frontend/src/EditUserProfile.tsx
> +    <span>Loading...</span>;
Add a return here
```suggestion
    return <span>Loading...</span>;
```

2023-12-30 16:35 UTC, soumitradev commented on frontend/src/EditUserProfile.tsx
> +        }
Since these errors render components, handle all the alert errors in an `errorComponent`. See https://github.com/crux-bphc/chronofactorem-rewrite/blob/f2cf6b45aa1bc595731699d6b53ffe374142baea/frontend/src/Login.tsx#L37-L108 for an example.

2023-12-30 16:35 UTC, soumitradev commented on frontend/src/components/ui/button.tsx
Revert changes to this file, you can just copy paste it from master and save it without formatting

2023-12-30 16:35 UTC, soumitradev commented on frontend/src/components/ui/select.tsx
Revert changes to this file, you can just copy paste it from master and save it without formatting

2023-12-30 17:21 UTC, JustAGhost23 commented on frontend/src/components/ui/button.tsx
Reverted in [b52e184](https://github.com/crux-bphc/chronofactorem-rewrite/pull/117/commits/b52e1844aa55b886ac1af25d09744680463bf453)

2023-12-30 17:21 UTC, JustAGhost23 commented on frontend/src/components/ui/select.tsx
Reverted in [b52e184](https://github.com/crux-bphc/chronofactorem-rewrite/pull/117/commits/b52e1844aa55b886ac1af25d09744680463bf453)

2023-12-30 17:23 UTC, JustAGhost23 commented on frontend/src/EditUserProfile.tsx
> +    <span>Loading...</span>;
Done in [3e1740f](https://github.com/crux-bphc/chronofactorem-rewrite/pull/117/commits/3e1740f375f494253266e8b3169f4af4401927ed)

2023-12-30 17:41 UTC, JustAGhost23 commented on frontend/src/EditUserProfile.tsx
> +                <SelectTrigger className="w-84 lg:mx-4 bg-slate-800 border-slate-700 focus:ring-slate-800 focus:ring-offset-slate-800 text-slate-50 mt-2">
Done in [18609f1](https://github.com/crux-bphc/chronofactorem-rewrite/pull/117/commits/18609f1f5d8a202c1be08e707cf7a730855610e1)

2023-12-30 17:41 UTC, JustAGhost23 commented on frontend/src/EditUserProfile.tsx
> +          <div className="flex lg:flex-row flex-col">
Done in [18609f1](https://github.com/crux-bphc/chronofactorem-rewrite/pull/117/commits/18609f1f5d8a202c1be08e707cf7a730855610e1)

2023-12-30 17:42 UTC, JustAGhost23 commented on frontend/src/EditUserProfile.tsx
> +          <div className="rounded-full text-slate-50 bg-slate-500 lg:px-9 lg:py-6 lg:text-6xl px-7 py-4 text-4xl lg:h-28 lg:w-28 h-20 w-20 lg:mx-4 mx-2 lg:mt-4 lg:mb-8 mt-2 mt-4">
Done in [18609f1](https://github.com/crux-bphc/chronofactorem-rewrite/pull/117/commits/18609f1f5d8a202c1be08e707cf7a730855610e1)

2023-12-30 17:49 UTC, JustAGhost23 commented on frontend/src/EditUserProfile.tsx
> +              <Select onValueChange={setSecondDegree}>
Done in [a3a6bf3](https://github.com/crux-bphc/chronofactorem-rewrite/pull/117/commits/a3a6bf3d96811a34b57ba697f973ee2269cab3cb)

2023-12-30 17:49 UTC, JustAGhost23 commented on frontend/src/EditUserProfile.tsx
> +            )}
Done in [a3a6bf3](https://github.com/crux-bphc/chronofactorem-rewrite/pull/117/commits/a3a6bf3d96811a34b57ba697f973ee2269cab3cb)

2023-12-30 17:56 UTC, JustAGhost23 commented on frontend/src/EditUserProfile.tsx
> +            <span>{userQueryResult.data.name[0]}</span>
Done in [0d4e410](https://github.com/crux-bphc/chronofactorem-rewrite/pull/117/commits/0d4e41058344a66880238672e17b36153cf21ef3)

2023-12-30 18:50 UTC, JustAGhost23 commented on frontend/src/EditUserProfile.tsx
> +        }
Done in [03e6a79](https://github.com/crux-bphc/chronofactorem-rewrite/pull/117/commits/03e6a794ecf6eebf5350070e99d3c135d5c5aef5), kindly go through and confirm.

2023-12-31 05:03 UTC, soumitradev commented on frontend/src/components/ui/select.tsx
File still had a new line at the end, reverted that in d1081bb

2023-12-31 05:03 UTC, soumitradev commented on frontend/src/components/ui/button.tsx
File still had a new line at the end, reverted that in d1081bb

2023-12-31 05:05 UTC, soumitradev requested changes
One last thing before I merge this PR: color standardization. You can look at #91 for an example, the code there is updated to use the standard colors for the same components.

2023-12-31 05:48 UTC, soumitradev approved these changes
LGTM

2023-12-31 05:48 UTC, merged