Add timetable grid component
crux-bphc/chronofactorem-rewrite pull request #129
Opened 2023-12-31 18:17 UTC by skoriop

2024-01-01 13:54 UTC, soumitradev requested changes
Few small changes, and in addition to this I'd like you to implement 1 more thing:
- The latest known section was actually in hour 13, and not hour 11. Edit the conditional rendering part to accommodate for sections as late as hour 13 (i.e. 8PM - 9PM).

2024-01-01 13:54 UTC, soumitradev commented on frontend/src/components/TimetableGrid.tsx
> +    <div className="ml-4 flex w-full">
```suggestion
    <div className="flex w-full">
```
Remove this margin, if the parent component wants to add spacing it can do so with padding anyways.

2024-01-01 13:54 UTC, soumitradev commented on frontend/src/components/TimetableGrid.tsx
> +              .filter((e, i) => i < displayCols)
```suggestion
              .filter((_, i) => i < displayCols)
```
rename unused var

2024-01-01 13:54 UTC, soumitradev commented on frontend/src/components/TimetableGrid.tsx
> +            .filter((e, i) =>
```suggestion
            .filter((_, i) =>
```
rename unused var

2024-01-01 13:54 UTC, soumitradev commented on frontend/src/components/TimetableGrid.tsx
> +                      className={`bg-primary-foreground border cursor-pointer transition duration-200 ease-in-out text-foreground/65 p-1.5 ${
```suggestion
                      className={`bg-background border border-muted/70 cursor-pointer transition duration-200 ease-in-out text-foreground/65 p-1.5 ${
```
Make the background completely transparent, as the intended design is to mimic that of Google Calendar, if not now at least in the future. Reduce opacity of borders to make them more dull for the same reason.

2024-01-01 13:54 UTC, soumitradev commented on frontend/src/components/TimetableGrid.tsx
> +                          className="absolute top-1 right-1 sm:visible invisible hover:stroke-[#EF4444]"
```suggestion
                          className="absolute top-1 right-1 sm:visible invisible hover:stroke-destructive dark:hover:stroke-red-400 transition duration-100 ease-in-out"
```
Avoid use of custom colors, and add a slight transition.

2024-01-01 13:54 UTC, soumitradev commented on frontend/src/components/TimetableGrid.tsx
> +                  className={`bg-primary-foreground border ${
```suggestion
                  className={`bg-background border border-muted/70 ${
```
Same suggestion as before, make the background completely transparent and dull the borders.

2024-01-01 13:54 UTC, soumitradev commented on frontend/src/components/TimetableGrid.tsx
> +  const [displayRows, setDisplayRows] = useState(6);
```suggestion
  const displayRows = 6;
```
Since this is not changed anywhere, you can define it as constant.

2024-01-01 13:55 UTC, soumitradev commented
Beyond this, I think I should probably mention this somewhere, so I'm mentioning it in this PR. The parent page should set vertical to true automatically on any screen that is smaller than that specified by tailwind's `lg` size.

2024-01-01 13:58 UTC, soumitradev commented
Oh and also 2 more changes:
- Vertical view does not render the times, but it should. This was omitted in the old frontend because I couldn't get it to render properly by release.
- The X button does not appear on devices smaller than `sm`. The section should have a double-click handler to substitute for the functionality lost by not rendering that button

2024-01-02 07:53 UTC, skoriop commented on frontend/src/components/TimetableGrid.tsx
> +                      className={`bg-primary-foreground border cursor-pointer transition duration-200 ease-in-out text-foreground/65 p-1.5 ${
Done in 430fdf6. The borders looked very faint in light mode, so I kept them at full opacity. I also slightly dulled the day and timing indicators.

2024-01-02 07:54 UTC, skoriop commented on frontend/src/components/TimetableGrid.tsx
> +                  className={`bg-primary-foreground border ${
Same as above

2024-01-02 10:11 UTC, skoriop commented
> The X button does not appear on devices smaller than `sm`. The section should have a double-click handler to substitute for the functionality lost by not rendering that button.

Since the section already has a `handleUnitClick` click handler, I think this can be handled by the function passed in by the parent component (which is also what was done in the old frontend).

2024-01-02 15:58 UTC, soumitradev approved these changes
LGTM

2024-01-02 15:58 UTC, merged