Delete timetable id endpoint
crux-bphc/chronofactorem-rewrite pull request #13
Opened 2023-06-24 15:38 UTC by majimearun

2023-06-24 15:39 UTC, majimearun commented
weird

2023-06-25 11:59 UTC, soumitradev submitted a review, later dismissed
Move to builder syntax for DB calls

2023-06-25 11:59 UTC, soumitradev commented on src/controllers/timetable/create.ts
Change name of file to match function name

2023-06-25 11:59 UTC, soumitradev commented on src/controllers/timetable/delete.ts
Change name of file to match function name

2023-06-25 11:59 UTC, soumitradev commented on src/entity/Section.ts
> +    eager: true,
Remove eager here

2023-06-25 11:59 UTC, soumitradev commented on src/entity/Timetable.ts
> +  @ManyToMany(() => Section, (section) => section.timetables, { eager: true })
Reconsider eager fetches

2023-06-25 11:59 UTC, soumitradev commented on src/entity/User.ts
> +  @OneToMany(() => Timetable, (timetable) => timetable.author, { eager: true })
Reconsider eager fetches

2023-06-25 15:07 UTC, majimearun commented on src/controllers/timetable/create.ts
Done

2023-06-25 15:07 UTC, majimearun commented on src/controllers/timetable/delete.ts
Done

2023-06-25 15:07 UTC, majimearun commented on src/entity/Section.ts
> +    eager: true,
Done

2023-06-25 15:07 UTC, majimearun commented on src/entity/Timetable.ts
> +  @ManyToMany(() => Section, (section) => section.timetables, { eager: true })
Done

2023-06-25 15:08 UTC, majimearun commented on src/entity/User.ts
> +  @OneToMany(() => Timetable, (timetable) => timetable.author, { eager: true })
Done

2023-06-26 06:19 UTC, Anurav-Garg requested changes
Fix the problems with timetable creation as mentioned in comments~

2023-06-26 06:19 UTC, Anurav-Garg commented on src/controllers/timetable/createTimetable.ts
> +  const timetable: Timetable = await timetableRepository.create({
Something about the auto-incrementing timetable ID is broken; after making a couple timetables, then deleting one, trying to create another timetable gives an error about duplicate keys.

2023-06-26 06:19 UTC, Anurav-Garg commented on src/controllers/timetable/createTimetable.ts
> +  const timetable: Timetable = await timetableRepository.create({
Put db calls in a try-catch block, as currently an error disconnects from DB entirely and stops any further requests from being made.

2023-06-26 06:20 UTC, majimearun commented on src/controllers/timetable/createTimetable.ts
> +  const timetable: Timetable = await timetableRepository.create({
whats the error

2023-06-26 08:27 UTC, majimearun commented on src/controllers/timetable/createTimetable.ts
> +  const timetable: Timetable = await timetableRepository.create({
Done

2023-06-26 08:27 UTC, majimearun commented on src/controllers/timetable/createTimetable.ts
> +  const timetable: Timetable = await timetableRepository.create({
Done, and for all db interactions, not just this

2023-06-26 09:32 UTC, Anurav-Garg commented on src/controllers/timetable/createTimetable.ts
> +    try {
If there's a timetable with name "Draft [non integer value]" the try-catch isn't triggered (JavaScript moment), JS just returns NaN instead. As such timetable creation proceeds as normal and returns this:
![image](https://github.com/crux-bphc/chronofactorem-rewrite/assets/106542270/583a4f84-fe28-4e18-93d9-2a4228e87ad1)
Trying to create another timetable after this errors out only because it tries to create another tt with the same name.

2023-06-26 09:50 UTC, majimearun commented on src/controllers/timetable/createTimetable.ts
> +    try {
fixed using a filter instead of a try-catch block

2023-06-26 10:17 UTC, Anurav-Garg approved these changes
Seems to work~

2023-06-26 10:18 UTC, merged

2023-06-26 16:25 UTC, soumitradev commented
Not happy with a bunch of code in this PR, reverting.

2023-06-26 16:26 UTC, soumitradev commented
Your branch has been restored, make a new PR and we'll work on merging this again from there.