Implement oauth
crux-bphc/chronofactorem-rewrite pull request #15
Opened 2023-06-24 18:36 UTC by Shre-D

Adds authentication and stores users on a database.

2023-06-25 10:57 UTC, soumitradev commented
From 02d7bcd onwards some of the commits use past tense for their commit messages, please rebase and reword these commits

2023-06-26 17:27 UTC, soumitradev requested changes
See comments

2023-06-26 17:27 UTC, soumitradev commented on src/config/authClient.ts
> +      redirect_uris: ["http://localhost:3000/auth/callback"],
Use `env.PROD_URL` here, and replace your env prod url with `http://localhost:3000`

2023-06-26 17:27 UTC, soumitradev commented on src/controllers/user/auth.ts
> +      res.redirect("http://localhost:3000/auth/callback");
Again, use `env.PROD_URL` here

2023-06-26 17:27 UTC, soumitradev commented on src/controllers/user/auth.ts
> +      //tokenSet contains the refresh_token and access_token codes
Again, the code comments not having spaces thing

2023-06-26 17:27 UTC, soumitradev commented on src/controllers/user/auth.ts
> +        "http://localhost:3000/auth/callback",
Again, use `env.PROD_URL` here

2023-06-26 17:27 UTC, soumitradev commented on src/controllers/user/auth.ts
> +      //obtaining the acces_token from tokenSet
typo + space between comment and slash

2023-06-26 17:27 UTC, soumitradev commented on src/controllers/user/auth.ts
> +const code_verifier = generators.codeVerifier();
use camelCase for vars

2023-06-26 17:27 UTC, soumitradev commented on src/controllers/user/auth.ts
> +      const code_challenge = generators.codeChallenge(code_verifier);
use camelCase for vars

2023-06-26 17:27 UTC, soumitradev commented on src/controllers/user/auth.ts
> +      const auth_redirect = client.authorizationUrl({
use camelCase for vars

2023-06-26 17:27 UTC, soumitradev commented on src/controllers/user/auth.ts
> +      //obtaining userinfo from the access_token code
space between comment and slash

2023-06-26 17:27 UTC, soumitradev commented on src/controllers/user/auth.ts
> +      const userinfo = await client.userinfo(access_token as string | TokenSet);
use camelCase for vars

2023-06-26 17:27 UTC, soumitradev commented on src/controllers/user/auth.ts
> +      //defines maxAge to be the time when the session cookie expires
space between comment and slash

2023-06-26 17:27 UTC, soumitradev commented on src/controllers/user/auth.ts
> +      const maxAge = tokenExpiryTime * 1000 - Date.now(); //converts into milliseconds
space between comment and slash

2023-06-26 17:27 UTC, soumitradev commented on src/controllers/user/auth.ts
> +      //setting the cookie
space between comment and slash

2023-06-26 17:27 UTC, soumitradev commented on src/controllers/user/auth.ts
> +  /*this function is declared outside the try
Don't use multiline comments, use multiple one-line comments

2023-06-26 17:27 UTC, soumitradev commented on src/controllers/user/auth.ts
> +    //gets userinfo as part of session
space between comment and slash

2023-06-26 17:27 UTC, soumitradev commented on src/controllers/user/auth.ts
> +    // console.log(userData);
remove this comment

2023-06-26 17:27 UTC, soumitradev commented on src/controllers/user/auth.ts
> +    //slices mail to obtain batch
space between comment and slash

2023-06-26 17:27 UTC, soumitradev commented on src/controllers/user/auth.ts
> +    //converts name to title case
space between comment and slash

2023-06-26 17:27 UTC, soumitradev commented on src/controllers/user/auth.ts
> +    /*
Don't use multiline comments, use multiple one-line comments

2023-06-26 17:27 UTC, soumitradev commented on src/controllers/user/auth.ts
> +    userRepository.insert({
Migrate this to query builder pattern, we are migrating the repo to it

2023-06-26 17:27 UTC, soumitradev commented on src/controllers/user/auth.ts
> +//this function deletes the session cookie to log out
space between comment and slash

2023-06-26 17:27 UTC, soumitradev commented on src/controllers/user/auth.ts
> +/* On any route, when checking if a user is logged in, check for the cookie
Don't use multiline comments, use multiple one-line comments, also I don't think you should have explanatory comments at the bottom of the file. If you really need these comments, move it to the top of the file

2023-06-29 12:55 UTC, soumitradev approved these changes
There's still two snake case variables in here, but I'll fix it while integrating auth with the rest of the endpoints. Good job, LGTM, merging.

2023-06-29 12:55 UTC, merged

2023-06-29 12:59 UTC, megz15 commented
> There's still two snake case variables in here, but I'll fix it while integrating auth with the rest of the endpoints. Good job, LGTM, merging.

Changing those vars to camelCase breaks node-openid-client for some reason