"Update section and timetable tables when course timings change"
crux-bphc/chronofactorem-rewrite pull request #174
Opened 2024-02-21 18:20 UTC by kishan1735

2024-02-22 06:07 UTC, soumitradev requested changes
Some small code-style related changes, overall code quality looks good. The main logic can be replaced by a lot of existing code/function calls.

One small note on your commits:
Your commit is:
`feat: update timetable and sections table when there is change in course timings`
It would ideally be:
`feat: add update changed timetables endpoint`

2024-02-22 06:07 UTC, soumitradev commented on backend/src/controllers/timetable/updateChangedTimetable.ts
> +    }
This part is pretty unreadable and complex. It can be simplified a lot: all this part needs to do is:
1. If any exam timings are updated (you can set a boolean for this up there that you check over here), for each timetable, remove the old exam timings of the course using https://github.com/crux-bphc/chronofactorem-rewrite/blob/266906137c0cef64dc905c3ca7651b0b14431c36/backend/src/controllers/timetable/removeSection.ts#L146-L151. Then, after the old exam timings are removed, you can use this function to check if the new exam timings clash: https://github.com/crux-bphc/chronofactorem-rewrite/blob/266906137c0cef64dc905c3ca7651b0b14431c36/backend/src/utils/checkForClashes.ts#L39. If the new timings clash, remove all the sections of this course from the timetable, make it a draft, save it, and return. If they don't clash, save the exam timings using https://github.com/crux-bphc/chronofactorem-rewrite/blob/266906137c0cef64dc905c3ca7651b0b14431c36/backend/src/controllers/timetable/addSection.ts#L201-L208.
2. For each timetable, run a for loop for all the sections, and if the timetable contains the section, remove the section's timings using https://github.com/crux-bphc/chronofactorem-rewrite/blob/266906137c0cef64dc905c3ca7651b0b14431c36/backend/src/controllers/timetable/removeSection.ts#L173-L183. Then, after the old timings are removed, you can use this function to check if the new timings clash: https://github.com/crux-bphc/chronofactorem-rewrite/blob/266906137c0cef64dc905c3ca7651b0b14431c36/backend/src/utils/checkForClashes.ts#L3. If the new timings clash, remove this section from the timetable, make it a draft. If they don't clash, save the exam timings using https://github.com/crux-bphc/chronofactorem-rewrite/blob/266906137c0cef64dc905c3ca7651b0b14431c36/backend/src/controllers/timetable/addSection.ts#L197-L199. At the end of the inner section for loop, you can save the timetable.

 **A lot of this logic is duplicated from `removeSection` and `addSection`, so make sure you extract the common code that you copy from there to a new file in `utils`.**

2024-04-08 06:18 UTC, soumitradev commented
I'll review this PR during this week most probably.

2024-05-22 08:35 UTC, soumitradev commented on backend/src/controllers/timetable/updateChangedTimetable.ts
> +} from "../../../../lib/src/index.js";
Resolved in 1ce5129

2024-05-22 08:35 UTC, soumitradev commented on backend/src/controllers/timetable/updateChangedTimetable.ts
> +    const course: Course | null = req.body.course;
Resolved in 1ce5129

2024-05-22 08:35 UTC, soumitradev commented on backend/src/controllers/timetable/updateChangedTimetable.ts
> +import { Course, Section, Timetable, User } from "../../entity/entities.js";
Resolved in 1ce5129

2024-05-22 08:35 UTC, soumitradev commented on backend/src/controllers/timetable/updateChangedTimetable.ts
> +    course: sectionWithCourseType,
Resolved in 1ce5129

2024-05-22 08:35 UTC, soumitradev commented on backend/src/controllers/timetable/updateChangedTimetable.ts
> +    console.log(course?.midsemStartTime);
Resolved in 1ce5129

2024-05-22 08:35 UTC, soumitradev commented on backend/src/controllers/timetable/updateChangedTimetable.ts
> +        .where("id=:id", { id: course?.id })
Resolved in 1ce5129

2024-05-22 08:36 UTC, soumitradev commented on backend/src/controllers/timetable/updateChangedTimetable.ts
> +      console.log("Error while querying for course: ", err.message);
Resolved in 1ce5129

2024-05-22 08:37 UTC, soumitradev commented on backend/src/controllers/timetable/updateChangedTimetable.ts
> +          .where("section.id=:id", { id: section?.id })
Resolved in 1ce5129

2024-05-22 08:37 UTC, soumitradev commented on backend/src/controllers/timetable/updateChangedTimetable.ts
> +    if (!timetables) {
Resolved in 1ce5129

2024-05-22 09:03 UTC, soumitradev requested changes
Aside from some small changes, LGTM. Would also be nice if we could wrap the whole thing in one transaction, like we do in addSection.ts

2024-05-22 09:03 UTC, soumitradev commented on backend/src/controllers/timetable/updateChangedTimetable.ts
> +      removeCourseExams(timetable, course);
Not sure why we are removing the course exams from a timetable unconditionally? Shouldn't this be done only when some clash has been found?

2024-05-25 04:30 UTC, kishan1735 commented on backend/src/controllers/timetable/updateChangedTimetable.ts
> +      removeCourseExams(timetable, course);
remove course exams removes only if the no of sections in the course is zero (u can check the function)

2024-05-30 16:46 UTC, soumitradev commented on backend/src/controllers/timetable/updateChangedTimetable.ts
> +              remSection(timetable, sec);
Resolved in 2d83639

2024-05-30 16:46 UTC, soumitradev commented on backend/src/controllers/timetable/updateChangedTimetable.ts
> +              await timetableRepository.save(timetable);
Resolved in 2d83639

2024-05-30 16:47 UTC, soumitradev commented on backend/src/controllers/timetable/updateChangedTimetable.ts
> +              removeCourseExams(timetable, course);
Resolved in 2d83639

2024-05-30 16:50 UTC, soumitradev commented on backend/src/controllers/timetable/updateChangedTimetable.ts
> +      removeCourseExams(timetable, course);
Either rename the function to appropriately fit what it does, or inline this logic and get rid of the function. As far as I can see, this is the only place this function is used, so we can just inline it instead of making it a separate function.

2024-05-30 16:52 UTC, kishan1735 commented on backend/src/controllers/timetable/updateChangedTimetable.ts
> +      removeCourseExams(timetable, course);
It is used at two places but yeah I ll rename

2024-05-30 16:58 UTC, kishan1735 commented on backend/src/controllers/timetable/updateChangedTimetable.ts
> +      removeCourseExams(timetable, course);
fixed it

2024-05-31 04:19 UTC, soumitradev commented on backend/src/controllers/timetable/updateChangedTimetable.ts
> +      removeCourseExams(timetable, course);
Resolved in f25ebbd

2024-05-31 08:43 UTC, soumitradev commented on backend/src/controllers/timetable/updateChangedTimetable.ts
> +        .getMany();
Resolved in 
179583a

2024-05-31 08:43 UTC, soumitradev commented on backend/src/controllers/timetable/updateChangedTimetable.ts
> +    }
Resolved in 1ce5129

2024-06-01 17:26 UTC, soumitradev approved these changes

2024-06-01 17:26 UTC, merged