Intgrated Akshat Oke's cms cred grabber extension
crux-bphc/chronofactorem-rewrite pull request #175
Opened 2024-02-24 17:14 UTC by NamitBhutani

2024-05-22 08:19 UTC, soumitradev requested changes
Oops, accidentally approved in my last review.

2024-05-22 08:21 UTC, soumitradev commented
Once this PR is merged, could you also refactor all the files to use a uniform naming convention for `CMS`? I've made a P2 issue for this in the release project.

2024-05-24 11:28 UTC, NamitBhutani commented on frontend/src/Cms.tsx
>                    </Button>
I feel that we can give users the ability to install the unpacked extension themselves, and fill in the custom extension ID.

2024-05-24 11:29 UTC, soumitradev commented on frontend/src/Cms.tsx
>                    </Button>
Trust me nobody wants the option to do this

2024-05-24 11:30 UTC, NamitBhutani commented on frontend/src/Cms.tsx
>                    </Button>
welp

2024-05-24 14:35 UTC, NamitBhutani commented
> Once this PR is merged, could you also refactor all the files to use a uniform naming convention for `CMS`? I've made a P2 issue for this in the release project.

oki sure.

2024-05-30 16:29 UTC, soumitradev approved these changes
Few small QoL changes, PR looks good otherwise.

2024-05-30 16:29 UTC, soumitradev commented on frontend/package.json
> +		"@types/chrome": "^0.0.268"
Move `@types/chrome` to prod dependency, since prod containers wont compile the code without the types, since the prod containers only fetch non-dev dependencies

2024-05-30 16:29 UTC, soumitradev commented on frontend/src/Cms.tsx
> +  const sesskeyFetchRef = useRef<string | null>(null);
So there's a bug right now that we need to fix, a possible improvement, and a change you can make to some of the logic on this page to achieve both:
- Bug: The actual requests on this page do not go through (for example clicking on the enroll in sections button will make a bunch of requests with the token as `undefined`), mostly because they still rely on the inputRefs, in the lines highlighted above. This bug is a pretty small fix now, but you can make it part of a bigger feature.
- Possible improvement: If the extension isn't working, allow them to press a button and go back to the old way of adding creds, using the inputs. Such a button could also have text like "Extension not working? Try the manual method." in case the extension isn't working.

By adding that one button to let users choose, you will probably add another state variable like `choseManualMethod` that is a boolean that indicates if we need to show those input boxes or not. Using this boolean, we can also standardize whether we want to use the HTMLInputElement refs for the credential values, or the FetchRefs. You can standardize all credential logic using that one boolean.

2024-05-30 16:29 UTC, soumitradev commented on frontend/src/Cms.tsx
> +                    allowEdit ? "blur-sm pointer-events-none" : ""
Change this to `blur-md`, it kinda messes with the text contrast as of now.

2024-05-30 16:29 UTC, soumitradev commented on frontend/src/Cms.tsx
> +                      allowEdit ? "blur-sm pointer-events-none" : ""
Change this to `blur-md`, it kinda messes with the text contrast as of now.

2024-05-30 16:29 UTC, soumitradev commented on frontend/src/Cms.tsx
> +                  </TooltipContent>
Edit this to talk about the extension as a first resort, instead of expecting them to follow the manual method.

2024-05-30 16:29 UTC, soumitradev commented on frontend/src/Cms.tsx
>                    </div>
This part can also be edited to ask people to download the extension first and resort to the manual method after.

2024-05-30 16:30 UTC, soumitradev requested changes
I think I'm getting old, I accidentally approved again.

2024-06-01 16:58 UTC, soumitradev commented on frontend/package.json
> +		"@types/chrome": "^0.0.268"
Resolved in d5bfbbc

2024-06-01 17:25 UTC, soumitradev commented
@NamitBhutani insane first PR, good shit

2024-06-01 17:25 UTC, soumitradev approved these changes

2024-06-01 17:26 UTC, merged