All courses endpoint
crux-bphc/chronofactorem-rewrite pull request #23
Opened 2023-06-27 08:30 UTC by divok11231

Added the the get all courses endpoint allowing users to get all existing courses

2023-06-27 08:42 UTC, majimearun requested changes

2023-06-27 08:42 UTC, majimearun commented on src/routers/courseRouter.ts
> +courseRouter.get("/course")
the route is `/`, cause its already mounted on `/course`

2023-06-27 08:42 UTC, majimearun commented on src/routers/courseRouter.ts
Add a validator for the request body

2023-06-27 08:42 UTC, majimearun commented on src/controllers/course/getAll.ts
Naming convention of the files changed. The file name should include the entity from what was decided in the last timetable PR. So `getAllCourses.ts`?

2023-06-27 08:42 UTC, majimearun commented on src/controllers/course/getAll.ts
> +  const courses = await courseRepository.find({});
We're using builder pattern across all db interactions for uniformity, so change this to builder pattern as well.

2023-06-27 08:42 UTC, majimearun commented on src/controllers/course/getAll.ts
> +  const courses = await courseRepository.find({});
Also wrap the db query in a try-catch block

2023-06-27 08:42 UTC, majimearun commented on src/controllers/course/get.ts
Naming convention of the files changed. The file name should include the entity from what was decided in the last timetable PR. So `getCourseByCode.ts`?

2023-06-27 08:42 UTC, majimearun commented on src/controllers/course/get.ts
i.e, it should match the function name

2023-06-27 08:42 UTC, majimearun commented on src/controllers/course/get.ts
> +  console.log(code);
Remove debug console log

2023-06-27 08:42 UTC, majimearun commented on src/controllers/course/get.ts
> +
Add validation for the request body and path params

2023-06-27 08:42 UTC, majimearun commented on src/controllers/course/get.ts
> +  });
We're using builder pattern across all db interactions for uniformity, so change this to builder pattern as well.

2023-06-27 08:42 UTC, majimearun commented on src/controllers/course/get.ts
> +  const course = await courseRepository.findOne({
Wrap the db query in a try-catch block

2023-06-27 08:42 UTC, majimearun commented on src/controllers/course/getAll.ts
> +    return res.json({ message: "no courses" });
Not 100% sure about this, but wouldn't it be better to set a different status instead of `200 OK` for this

2023-06-27 08:42 UTC, majimearun commented on src/controllers/course/getAll.ts
> +  console.log(courses);
Remove debug console log

2023-06-27 08:42 UTC, majimearun commented on src/controllers/course/get.ts
> +    return res.json({ message: "Course does not exist" });
Not 100% sure about this, but wouldn't it be better to set a different status instead of `200 OK` for this

2023-06-27 08:42 UTC, majimearun commented on src/controllers/course/get.ts
> +  console.log(course);
Remove debug console log

2023-06-29 04:58 UTC, soumitradev requested changes

2023-06-29 04:58 UTC, soumitradev commented on src/controllers/course/getCourseByCode.ts
> +const paramsSchema = z.object({
follow the validation pattern we use in #5

2023-06-29 04:58 UTC, soumitradev commented on src/routers/courseRouter.ts
> +courseRouter.get("/:code", getCourseByCode);
We can't use course code to fetch courses anymore, you need to use the ID

2023-06-29 13:56 UTC, soumitradev requested changes
minor changes requested

2023-06-29 13:56 UTC, soumitradev commented on src/controllers/course/getAllCourses.ts
> +      return res.json({ message: "No courses" });
make this status 404

2023-06-29 13:56 UTC, soumitradev commented on src/controllers/course/getCourseById.ts
> +    id: z.string().min(0,{message:"id must be non-empty string"}).regex(/^\d+$/)
make this a number, and use `.coerce` for it, don't use a regex

2023-06-29 13:56 UTC, soumitradev commented on src/controllers/course/getCourseById.ts
> +      .createQueryBuilder("Course")
lowercase this alias, make it `course`, and do the same on the next line

2023-06-29 13:56 UTC, soumitradev commented on src/controllers/course/getCourseById.ts
> +      return res.json({ message: "Course does not exist" });
make this status 404

2023-06-29 13:56 UTC, soumitradev commented on src/routers/courseRouter.ts
> +import { getAllCourses} from "../controllers/course/getAllCourses"
also looks like this file isnt formatted

2023-06-29 14:37 UTC, soumitradev requested changes
Fix validation and then you're good to go

2023-06-29 14:37 UTC, soumitradev commented on src/routers/courseRouter.ts
> +courseRouter.get("/:id", getCourseById);
- you've added validators to the wrong endpoint
- the validator is added before the actual function, not after

2023-06-29 14:54 UTC, soumitradev submitted a review, later dismissed
LGTM

2023-06-29 14:57 UTC, soumitradev approved these changes
fixed merge conflict with master, LGTM now

2023-06-29 14:58 UTC, merged