[WIP] Section endpoints
crux-bphc/chronofactorem-rewrite pull request #28
Opened 2023-06-29 05:19 UTC by majimearun

2023-06-30 18:47 UTC, soumitradev requested changes
gave this PR 2 full readings i dont get paid enough for this shit fr

2023-06-30 18:47 UTC, soumitradev commented on src/controllers/timetable/addSection.ts
> +        .where("timetable.id = :id", { id: timetable.id })
i'm pretty sure you can put this in the condition for the join itself, you don't need a separate where here

2023-06-30 18:47 UTC, soumitradev commented on src/controllers/timetable/addSection.ts
> +        .where("timetable.id = :id", { id: timetable.id })
technically for an inner join there's no diff between the two functionally, though if there was no query optimizer, the join condition would result in better performance

2023-06-30 18:47 UTC, soumitradev commented on src/controllers/timetable/addSection.ts
> +        message: `can't have multiple sections of type ${section.type}`,
just from a product or frontend perspective, it makes more sense to remove the previous section of this type, and add this section instead; you don't need the user to delete the previous section, and add this one or alternatively you don't need the frontend to make 2 requests to the backend everytime someone wants to switch a section

2023-06-30 18:47 UTC, soumitradev commented on src/controllers/timetable/addSection.ts
> +    console.log("Warnings:", timetable.warnings);
add a space after `Warnings:`

2023-06-30 18:47 UTC, soumitradev commented on src/controllers/timetable/addSection.ts
> +    section.roomTime.forEach((time) => {
once again i believe this can be converted to a .map() call to avoid more reallocations

2023-06-30 18:47 UTC, soumitradev commented on src/controllers/timetable/addSection.ts
> +          if (!examHourClashes.sameCourse) {
i think this query can be collapsed into the query where you update the sections on the timetable (line 243 rn) by using a `CASE WHEN`

2023-06-30 18:47 UTC, soumitradev commented on src/controllers/timetable/addSection.ts
> +              .where("timetable.id = :id", { id: timetable?.id })
if you already have the timetable object then use it, don't use its id; you used the object on the first query anyway

2023-06-30 18:47 UTC, soumitradev commented on src/controllers/timetable/deleteTimetable.ts
> +    if (timetable.authorId !== author.id) {
sexy

2023-06-30 18:47 UTC, soumitradev commented on tsconfig.json
> +    "lib": ["es5", "es6"],
revert formatting on this file, i think someone has a wrongly configured formatter

2023-06-30 18:47 UTC, soumitradev commented on src/utils/checkForClashes.ts
> +    if (timesMap.has(newTime)) {
instead of doing a `has` and `get` call separately, can't you just make it one `get` call and check for `undefined`?

2023-06-30 18:47 UTC, soumitradev commented on src/utils/checkForClashes.ts
> +  for (const [key, value] of examTimesMap) {
I feel like you should refactor this to a function, since its duplicated logic, but then again https://en.wikipedia.org/wiki/Rule_of_three_(computer_programming)

2023-06-30 18:47 UTC, soumitradev commented on src/utils/checkForClashes.ts
> +  for (const [key, value] of examTimesMap) {
so final decision: don't refactor, but if you feel like it, go ahead

2023-06-30 18:47 UTC, soumitradev commented on src/utils/updateWarnings.ts
> +      for (const currentSectionWarning of currentWarning!
non-null assert; generally a bad idea, so I'd like to know if its really needed in this case

2023-06-30 18:47 UTC, soumitradev commented on src/utils/updateWarnings.ts
> +          const index = currentWarning!.warningCourseSectionTypesSplit.indexOf(
another one

2023-06-30 18:47 UTC, soumitradev commented on src/utils/updateWarnings.ts
> +          currentWarning!.warningCourseSectionTypesSplit.splice(index!, 1);
another two! by god

2023-06-30 18:47 UTC, soumitradev commented on src/utils/updateWarnings.ts
> +          if (currentWarning!.warningCourseSectionTypesSplit.length == 0) {
another one

2023-06-30 18:47 UTC, soumitradev commented on src/utils/updateWarnings.ts
> +      //No warnings currently exist, thus adding new one for this section
add a space between slashes and the comment

2023-06-30 18:47 UTC, soumitradev commented on src/utils/updateWarnings.ts
> +      //Adding new courseType to warnings after removing course
add a space between slashes and the comment

2023-06-30 18:47 UTC, soumitradev commented on src/utils/updateWarnings.ts
> +    { warningCourseSectionTypesSplit: string[] }
why is `Split` needed in this variable name? I feel like it doesn't add a lot, and adds to the verbosity of the name

2023-06-30 18:47 UTC, soumitradev commented on src/utils/updateWarnings.ts
> +    const warningCourseSectionTypesSplit = warningCourseSectionTypes.split("");
same thing here

2023-06-30 18:47 UTC, soumitradev commented on src/utils/updateWarnings.ts
> +      const warningCourseSectionTypesList: string[] = [];
i feel like this can be converted to a `.map()`

2023-06-30 18:47 UTC, soumitradev commented on src/utils/updateWarnings.ts
> +        warningCourseSectionTypesList.sort();
why does it need to be sorted?

2023-06-30 18:47 UTC, soumitradev commented on src/utils/updateWarnings.ts
> +        currentWarningCourseSectionTypesSplit.sort();
one again, why does this need to be sorted?

2023-06-30 18:47 UTC, soumitradev commented on src/utils/updateWarnings.ts
> +  updatedWarnings.sort();
why do warnings need to be sorted?

2023-06-30 18:47 UTC, soumitradev commented on src/utils/checkForClashes.ts
> +  currentTimetable: Timetable,
nothing wrong with naming this just `timetable`

2023-06-30 18:47 UTC, soumitradev commented on src/utils/checkForClashes.ts
> +  currentTimetable: Timetable,
nothing wrong with naming this just `timetable`

2023-06-30 18:47 UTC, soumitradev commented on src/entity/Timetable.ts
> +  @Column({ type: "varchar", length: 20, array: true })
why are we increasing the length to 20? isnt 4 or 5 sufficient?

2023-06-30 18:47 UTC, soumitradev commented on src/controllers/timetable/addSection.ts
> +        message: `course clashes with ${examHourClashes.course}'s ${examHourClashes.exam}`,
should be `course's exam clashes with ...`

2023-06-30 18:53 UTC, Anurav-Garg commented on src/controllers/timetable/addSection.ts
> +    console.log("Warnings:", timetable.warnings);
ah this log was for testing, was supposed to remove it before pushing

2023-06-30 19:43 UTC, majimearun commented on src/controllers/timetable/addSection.ts
> +      author = await userRepository
yepp, will do the perf testing after auth integration

2023-06-30 19:44 UTC, majimearun commented on src/controllers/timetable/addSection.ts
> +        .createQueryBuilder("course")
yepp, will do the perf testing after auth integration

2023-06-30 19:45 UTC, majimearun commented on src/utils/checkForClashes.ts
> +  currentTimetable: Timetable,
Jason removed it

2023-06-30 19:48 UTC, majimearun commented on src/controllers/timetable/addSection.ts
> +        message: `course clashes with ${examHourClashes.course}'s ${examHourClashes.exam}`,
updated

2023-06-30 19:52 UTC, majimearun commented on src/entity/Timetable.ts
> +  @Column({ type: "varchar", length: 20, array: true })
I need the course codes as well, to give proper messages in the response, so it can go upto like `CHEM F313:Th10`, (14 chars) so I allowed room for a couple more, reduced it to 15

2023-06-30 19:55 UTC, majimearun commented on src/utils/checkForClashes.ts
> +  currentTimetable: Timetable,
changed

2023-06-30 19:55 UTC, majimearun commented on src/utils/checkForClashes.ts
> +  currentTimetable: Timetable,
updated

2023-06-30 19:56 UTC, majimearun commented on src/utils/updateWarnings.ts
> +  updatedWarnings.sort();
removed

2023-06-30 19:56 UTC, majimearun commented on src/utils/updateWarnings.ts
> +        currentWarningCourseSectionTypesSplit.sort();
removed

2023-06-30 19:57 UTC, majimearun commented on src/utils/updateWarnings.ts
> +    { warningCourseSectionTypesSplit: string[] }
changed

2023-06-30 19:57 UTC, majimearun commented on src/utils/updateWarnings.ts
> +    const warningCourseSectionTypesSplit = warningCourseSectionTypes.split("");
changed

2023-06-30 19:59 UTC, majimearun commented on src/controllers/timetable/addSection.ts
> +        message: `can't have multiple sections of type ${section.type}`,
Will wait for remove to work on this as it'll have common functions and handling of various cases. But will defintely come back to this yes.

2023-06-30 20:00 UTC, majimearun commented on src/controllers/timetable/addSection.ts
> +    console.log("Warnings:", timetable.warnings);
removed

2023-06-30 20:02 UTC, majimearun commented on src/controllers/timetable/addSection.ts
> +    section.roomTime.forEach((time) => {
shifted

2023-06-30 20:02 UTC, majimearun commented on src/controllers/timetable/addSection.ts
> +          response.forEach((sectionType) => {
shifted

2023-06-30 20:05 UTC, majimearun commented on src/controllers/timetable/deleteTimetable.ts
> +    if (timetable.authorId !== author.id) {
very helpful

2023-06-30 20:12 UTC, majimearun commented on src/utils/updateWarnings.ts
> +      const warningCourseSectionTypesList: string[] = [];
used a filter

2023-06-30 20:12 UTC, majimearun commented on src/utils/updateWarnings.ts
> +      //Adding new courseType to warnings after removing course
done

2023-06-30 20:12 UTC, majimearun commented on src/utils/updateWarnings.ts
> +      //No warnings currently exist, thus adding new one for this section
done

2023-06-30 20:14 UTC, majimearun commented on src/utils/checkForClashes.ts
> +  for (const [key, value] of examTimesMap) {
cool, anyways once all code is functional we'll have to go through refactoring and testing. So if needed we'll do it the time.

2023-06-30 20:20 UTC, majimearun commented on src/utils/checkForClashes.ts
> +    if (timesMap.has(newTime)) {
removed and rechecked if code still works.

2023-06-30 20:23 UTC, majimearun commented on src/controllers/timetable/addSection.ts
> +              .where("timetable.id = :id", { id: timetable?.id })
removed the assert, as it was unnecessary, but I didn't understand what you're saying. I am using the timetable object.

2023-06-30 20:26 UTC, majimearun commented on src/controllers/timetable/addSection.ts
> +          if (!examHourClashes.sameCourse) {
IMO it'll get less readable even if possible.

2023-06-30 20:29 UTC, majimearun commented on tsconfig.json
> +    "lib": ["es5", "es6"],
that someone would be me. though I dont know why. I am using prettier after all, and we have a config file.

2023-07-01 07:18 UTC, soumitradev commented on src/controllers/timetable/addSection.ts
> +          if (!examHourClashes.sameCourse) {
it might get less readable but will have better performance

2023-07-01 07:19 UTC, soumitradev commented on src/controllers/timetable/addSection.ts
> +              .where("timetable.id = :id", { id: timetable?.id })
instead of using `timetable.id` you can directly use `where(timetable)` like in previous queries

2023-07-01 07:21 UTC, soumitradev commented on tsconfig.json
> +    "lib": ["es5", "es6"],
my bad, I just checked my vscode settings and looks like my formatter was not correctly configured. you can keep the changes to this file.

2023-07-01 07:30 UTC, soumitradev requested changes
.map() is not being used correctly, and there's an extra callback function that doesn't really need to exist

2023-07-01 07:30 UTC, soumitradev commented on src/controllers/timetable/addSection.ts
> +          response.map((sectionType) => {
this is not how you use.map() lol
```ts
const a = [1, 2, 3, 4, 5];
const b = [];
for (let i = 0; i < a.length(); i++) {
  b.push(a[i] * 2)
}
```
becomes
```ts
const a = [1, 2, 3, 4, 5];
const b = a.map((x) => x*2);
```

2023-07-01 07:30 UTC, soumitradev commented on src/controllers/timetable/addSection.ts
> +    section.roomTime.map((time) => {
once again, not how you use .map()

2023-07-01 07:30 UTC, soumitradev commented on src/controllers/timetable/addSection.ts
>          .then((response) => {
also is this callback really needed?

2023-07-01 07:41 UTC, majimearun commented on src/controllers/timetable/addSection.ts
> +          response.map((sectionType) => {
lmao mb, sleepy coding things.

2023-07-01 07:41 UTC, majimearun commented on src/controllers/timetable/addSection.ts
> +          response.map((sectionType) => {
fixed

2023-07-01 07:50 UTC, soumitradev requested changes
went through code again, found a few more issues

2023-07-01 07:50 UTC, soumitradev commented on src/utils/updateWarnings.ts
> +          currentWarning.warningSectionTypes.splice(index!, 1);
non-null assert

2023-07-01 07:50 UTC, soumitradev commented on src/utils/updateWarnings.ts
> +          if (currentWarning.warningSectionTypes.length == 0) {
non-strict equality check

2023-07-01 07:50 UTC, soumitradev commented on src/utils/updateWarnings.ts
> +        if (requiredSectionTypes.length != currentWarningSectionTypes.length) {
non-strict equality check (i know it makes no difference here, but for the sake of uniformity)

2023-07-01 07:50 UTC, soumitradev commented on src/entity/Timetable.ts
> +  @Column({ type: "varchar", length: 20, array: true })
In that case, make this length some 35, since we're allowing course codes to go up to length 30.

2023-07-01 07:50 UTC, soumitradev commented on src/entity/Timetable.ts
>    @Column({ type: "varchar", length: 30, array: true })
Make this length 34 (30 for course code + 4 for the warning max chars), I should have done that in the ingestion PR.

2023-07-01 07:50 UTC, soumitradev commented on src/entity/Timetable.ts
> +  examTimes!: string[];
make this max length 80: 24 each for the timestamps = 48 + 2 for the separators = 50 + 30 for course code = 80

2023-07-01 07:50 UTC, soumitradev commented on src/utils/updateWarnings.ts
> +        if (sectionType == currentSectionWarning) {
non-typesafe comparison

2023-07-01 07:50 UTC, soumitradev commented on src/utils/updateWarnings.ts
> +          return requiredSectionType != sectionType;
non-typesafe comparison

2023-07-01 07:50 UTC, soumitradev commented on src/utils/updateWarnings.ts
> +      if (warningSectionTypesList.length != 0) {
non-typesafe comparison

2023-07-01 07:50 UTC, soumitradev commented on src/ingest.ts
There's a bunch of non-typesafe comparisons in this file as well, can you fix that as well? Just search for `==` and `!=` matching whole words in this file and you'll find them easily.

2023-07-01 08:13 UTC, majimearun commented on src/controllers/timetable/addSection.ts
> +        .distinctOn(["section.type"])
there multiple numbers for each section (L1, L2 P1, P2, T1, T2 etc.), but only one of each type is required. Hence the `distinctOn`

2023-07-01 08:20 UTC, majimearun commented on src/controllers/timetable/addSection.ts
> +        .where("timetable.id = :id", { id: timetable.id })
https://stackoverflow.com/questions/1018952/condition-within-join-or-where

even if query optimizer is present, both queries are mostly optimized the same. It's even recommended to keep them separate

2023-07-01 08:21 UTC, majimearun commented on src/controllers/timetable/addSection.ts
>          .then((response) => {
wdym. the query returns the sections, we just need the type

2023-07-01 08:28 UTC, majimearun commented on src/controllers/timetable/addSection.ts
> +          if (!examHourClashes.sameCourse) {
Two more reasons not to

1. maintainability: there's no docs for using CASE when except in gh issues. And even there the example is extremely simple. Ours is little more complicated as it requires string parsing.

2. the syntax for both queries are very different, since one is updating a foreign key using `.on(relation)` and `.add()`, and the other is using normal `.execute()`. im not that familiar with typeORM, so feels like making these into one query will be hard unless I write the SQL by hand.

2023-07-01 08:33 UTC, soumitradev requested changes
remove unnecessary callback

2023-07-01 08:33 UTC, soumitradev commented on src/controllers/timetable/addSection.ts
>          .then((response) => {
yeah but why do that in a callback, just do that in the same function

2023-07-01 08:33 UTC, soumitradev commented on src/controllers/timetable/addSection.ts
> +          if (!examHourClashes.sameCourse) {
the 2nd one is a little more convincing, but i'll try doing this in perf testing

2023-07-01 08:45 UTC, soumitradev approved these changes
LGTM, merging

2023-07-01 08:46 UTC, merged