Implement getPublicTimetables endpoint
crux-bphc/chronofactorem-rewrite pull request #31
Opened 2023-06-29 21:49 UTC by palaniappan-r

branch[] , year and sem should be passed as query parameters. If query parameters are not passed, all timetables will be returned.

2023-06-30 03:59 UTC, majimearun requested changes
Besides the small changes requested, looks good. Like mentioned in the comments, if there's a reason why you've written queries the way you did, please mention it

2023-06-30 03:59 UTC, majimearun commented on src/controllers/timetable/getPublicTimetables.ts
> +        timetables = await queryBuilder.getMany();
You don't have to wrap each where clause in a try-ctach block. The error message should contain the required information regardless. Wrap each db interaction/query in one try-ctach. If there is something you read which told you that this is the right practice, do share. So the rest of us can follow it as well.

2023-06-30 03:59 UTC, majimearun commented on src/controllers/timetable/getPublicTimetables.ts
> +    query : z.object({
No auth temp replacement or using the cookie either?

2023-06-30 03:59 UTC, majimearun commented on src/controllers/timetable/getPublicTimetables.ts
> +        branch: z.array(z.string())
We already have a degree enum, use that to validate

2023-06-30 03:59 UTC, majimearun commented on src/controllers/timetable/createTimetable.ts
> +          lastUpdated
The `,` is from prettier which is we're using for uniformity lol

2023-07-01 04:57 UTC, palaniappan-r commented on src/controllers/timetable/getPublicTimetables.ts
> +        timetables = await queryBuilder.getMany();
You're right. Those try/catch blocks are redundant. Removed them now.

2023-07-01 04:57 UTC, palaniappan-r commented on src/controllers/timetable/getPublicTimetables.ts
> +        branch: z.array(z.string())
Done

2023-07-01 08:06 UTC, soumitradev commented
I'll be reviewing this, since aruna is busy on #28

2023-07-01 08:13 UTC, soumitradev requested changes
format your code using Prettier, and resolve some other issues

2023-07-01 08:13 UTC, soumitradev commented on src/controllers/timetable/getPublicTimetables.ts
> +            required_error: "email is a required path parameter",
check #30 for a more fleshed-our version of these errors

2023-07-01 08:13 UTC, soumitradev commented on src/controllers/timetable/getPublicTimetables.ts
> +export const getPublicTimetables = async (req : Request , res : Response) => {
I don't think your code is formatted correctly, use Prettier

2023-07-01 08:13 UTC, soumitradev commented on src/controllers/timetable/getPublicTimetables.ts
> +            queryBuilder.andWhere("timetable.degrees = :branch", { branch })
I'm pretty sure you have to reassign queryBuilder to the return value of the function, you can't just call the function.

2023-07-01 08:13 UTC, soumitradev commented on src/controllers/timetable/getPublicTimetables.ts
> +            .select(["timetable.id", "timetable.name", "timetable.lastUpdated", "timetable.createdAt", "timetable.degrees"])
check #30 for the exact fields you need to select for timetable metadata

2023-07-01 09:00 UTC, palaniappan-r commented on src/controllers/timetable/getPublicTimetables.ts
> +            .select(["timetable.id", "timetable.name", "timetable.lastUpdated", "timetable.createdAt", "timetable.degrees"])
I'm selecting these fields for now, is this alright?

```
"timetable.id",
"timetable.name",
"timetable.degrees",
"timetable.private",
"timetable.draft",
"timetable.archived",
"timetable.acadYear",
"timetable.year",
"timetable.semester",
"timetable.createdAt",
"timetable.lastUpdated"
```

2023-07-01 09:25 UTC, palaniappan-r commented on src/controllers/timetable/getPublicTimetables.ts
> +            queryBuilder.andWhere("timetable.degrees = :branch", { branch })
It worked fine with timetables created by the `createTimetable` endpoint. [I manually added a dummy user in the db]

I've reassigned now though.

2023-07-01 09:27 UTC, soumitradev commented on src/controllers/timetable/getPublicTimetables.ts
> +            .select(["timetable.id", "timetable.name", "timetable.lastUpdated", "timetable.createdAt", "timetable.degrees"])
yes

2023-07-01 09:29 UTC, soumitradev submitted a review, later dismissed
LGTM

2023-07-01 09:29 UTC, soumitradev commented
resolving merge conflict, and merging

2023-07-01 09:32 UTC, soumitradev requested changes

2023-07-01 09:32 UTC, soumitradev commented on src/controllers/timetable/createTimetable.ts
Actually can you revert the change to this file? I'll merge after that

2023-07-01 09:36 UTC, soumitradev approved these changes

2023-07-01 09:36 UTC, soumitradev commented on src/controllers/timetable/createTimetable.ts
I formatted it instead

2023-07-01 09:37 UTC, merged