Create the removeSection endpoint
crux-bphc/chronofactorem-rewrite pull request #36
Opened 2023-07-01 16:47 UTC by Anurav-Garg

2023-07-01 17:10 UTC, soumitradev requested changes
Other than a couple of things, LGTM

2023-07-01 17:10 UTC, soumitradev commented on src/controllers/timetable/removeSection.ts
> +        .innerJoin("section.timetables", "timetable")
do you really need this join here? Instead you can check if section id exists in timetable.sections from line 87

2023-07-01 17:10 UTC, soumitradev commented on src/controllers/timetable/removeSection.ts
> +        .distinctOn(["section.type"])
is this distinctOn needed? don't we already assume they are distinct in the db?

2023-07-01 17:31 UTC, Anurav-Garg commented on src/controllers/timetable/removeSection.ts
> +        .distinctOn(["section.type"])
Yes it is needed, as this is querying all sections belonging to the course, not just the ones in the timetable

2023-07-01 17:52 UTC, Anurav-Garg commented on src/controllers/timetable/removeSection.ts
> +        .innerJoin("section.timetables", "timetable")
done

2023-07-01 17:54 UTC, soumitradev submitted a review, later dismissed
LGTM, will merge after #34

2023-07-02 13:25 UTC, soumitradev approved these changes
Refactored some minor stuff in PR to conform to ESLint rules, looks good now.

2023-07-02 13:26 UTC, merged