Add course unit tests, and refactor object and field zod definitions
crux-bphc/chronofactorem-rewrite pull request #42
Opened 2023-07-14 17:52 UTC by soumitradev

2023-07-25 03:33 UTC, Anurav-Garg reviewed
Slightly unrelated to the PR, but mentioning this since a similar issue was fixed in one of the commits here: the `/timetable/getPublic` endpoint doesn't work, as the `/timetable/:id` endpoint is placed before it in the router, so requests to this assume that "getPublic" is supposed to be a timetable ID.

2023-07-25 03:33 UTC, Anurav-Garg commented on src/controllers/course/getAllCourses.test.ts
> +  test("Test if database contains non-zero courses", () => {
Empty maps are truthy (JavaScript moment), so replacing `= null` in line 20 with `= new Map()`, and then commenting out the entire query test from line 22-29, still passes this test. Assuming an empty db would return an empty map, this test doesn't work.

2023-07-25 03:33 UTC, Anurav-Garg commented on src/controllers/course/getAllCourses.test.ts
> +    describe("Test response", () => {
Are two nested scopes of `describe()` really needed when each of them only have one item?

2023-07-25 03:33 UTC, Anurav-Garg commented on src/controllers/course/getCourseById.test.ts
> +    describe("Test response", () => {
Same as for `getAllCourses.test.ts`; Are two nested scopes of `describe()` really needed when each of them only have one item?

2023-07-25 08:10 UTC, soumitradev commented
> Slightly unrelated to the PR, but mentioning this since a similar issue was fixed in one of the commits here: the `/timetable/getPublic` endpoint doesn't work, as the `/timetable/:id` endpoint is placed before it in the router, so requests to this assume that "getPublic" is supposed to be a timetable ID.

Create an issue for this @Anurav-Garg

2023-07-25 08:22 UTC, soumitradev commented on src/types/zodFieldTypes.ts
> +      invalid_type_error: addNameToString("is not a number", name),
Fixed in 034595e

2023-07-25 08:27 UTC, soumitradev commented on src/types/zodFieldTypes.ts
> +      invalid_type_error: addNameToString("year is not a number", name),
About required error, fixed in 034595e
I don't think the LTE/GTE bounds makes sense, since this type could also be used for batches like `21` or `22`, or college years for timetables like `2` or `3`. Either we should make different types for all these, or document the many ways we use this type.

2023-07-25 08:27 UTC, soumitradev commented on src/types/zodFieldTypes.ts
> +      invalid_type_error: addNameToString("semester is not a number", name),
Fixed in 034595e

2023-07-25 08:33 UTC, soumitradev commented on src/entity/zod.ts
> +      type: NamedSectionTypeZodEnum(name),
They were already in PascalCase, so I left them that way. Should I rename them to be camelCase?

2023-07-25 08:50 UTC, soumitradev commented on src/types/zodFieldTypes.ts
> +      invalid_type_error: addNameToString("not a string", name),
Do you have a better solution?

2023-07-25 09:05 UTC, soumitradev commented on src/entity/zod.ts
> +export const namedCourseType = (name?: string) =>
Fixed in 92f76dd

2023-07-25 09:06 UTC, soumitradev commented on src/entity/zod.ts
> +      timings: namedNonEmptyStringType(addNameToString("timings", name)),
Fixed in 2ec415e

2023-07-25 09:11 UTC, soumitradev commented on src/controllers/course/getAllCourses.test.ts
> +  test("Test if database contains non-zero courses", () => {
Fixed in ef878bb.

2023-07-25 09:18 UTC, Anurav-Garg commented on src/types/zodFieldTypes.ts
> +      invalid_type_error: addNameToString("year is not a number", name),
Maybe different types would make more sense, since this way using the same type for both the examples you cited we could in theory have someone say they made their tt for their 23rd year of college and our backend would be fine with that

2023-07-25 09:18 UTC, soumitradev commented on src/controllers/course/getAllCourses.test.ts
> +    describe("Test response", () => {
Fixed in dbee3e9

2023-07-25 09:18 UTC, soumitradev commented on src/controllers/course/getCourseById.test.ts
> +    describe("Test response", () => {
Fixed in dbee3e9

2023-07-25 09:36 UTC, soumitradev commented on src/types/zodFieldTypes.ts
> +      invalid_type_error: addNameToString("year is not a number", name),
I suggest if we want to do this, we rename the type, and extend these to have some sensible defaults. So for example for year 2 or year 3, we could have a collegeYearType that extends the integer type and has some sensible limits like > 10 and < 50

2023-07-27 14:10 UTC, Anurav-Garg commented on src/types/zodFieldTypes.ts
> +      invalid_type_error: addNameToString("year is not a number", name),
Hmm, makes sense to me

2023-07-27 14:12 UTC, Anurav-Garg commented on src/entity/zod.ts
> +      type: NamedSectionTypeZodEnum(name),
To me at least it makes more sense to keep them uniform (either all PascalCase or all camelCase) unless there's a good reason not to

2023-07-27 14:38 UTC, Anurav-Garg commented on src/types/zodFieldTypes.ts
> +      invalid_type_error: addNameToString("not a string", name),
I suppose not

2023-07-28 05:07 UTC, soumitradev commented on src/types/zodFieldTypes.ts
> +      invalid_type_error: addNameToString("year is not a number", name),
Resolved in  c460a80

2023-07-28 05:14 UTC, soumitradev commented on src/entity/zod.ts
> +      type: NamedSectionTypeZodEnum(name),
Fixed in 2788cd8

2023-07-28 05:54 UTC, Anurav-Garg requested changes

2023-07-28 05:54 UTC, Anurav-Garg commented on src/types/zodFieldTypes.ts
> +    .gte(2000);
I think something like 1900 may be better for the lower limit here, rn we aren't using it like that but as this is the generic year type technically one could imagine a future where we save something like student or prof birth dates or something? Like yes not those things exactly, chrono has no need for those, but point is years before 2000 _may_ still be relevant sometimes, and if we're playing super safe with the upper limit at 3000 no reason not to be safer with the lower limit too imo

2023-07-28 05:57 UTC, soumitradev commented on src/types/zodFieldTypes.ts
> +    .gte(2000);
Resolved in b9a16052bf831693f74720a8be0a3e59aff24a08

2023-07-28 06:09 UTC, Anurav-Garg approved these changes
LGTM

2023-07-28 06:10 UTC, merged