Tests for editTimetableMetadata endpoint
crux-bphc/chronofactorem-rewrite pull request #50
Opened 2023-07-30 07:20 UTC by TheComputerM

2023-07-30 07:31 UTC, TheComputerM commented
Some questions:
- Is it really necessary to hard-code the response body messages in the tests
- Can we call the request directly in the `describe` block instead of calling it in a `test` block  and doing `response: Response | null`. Even if we do it in a seperate block, why not use `beforeAll` to call the api endpoint?

PS: thanks karthik I copied a ton of your stuff

2023-07-30 08:11 UTC, majimearun commented
> Some questions:
> 
>     * Is it really necessary to hard-code the response body messages in the tests
> 
>     * Can we call the request directly in the `describe` block instead of calling it in a `test` block  and doing `response: Response | null`. Even if we do it in a seperate block, why not use `beforeAll` to call the api endpoint?
> 
> 
> PS: thanks karthik I copied a ton of your stuff

Lmao okay first off, yes thank you karthik, I changed my testing code structure now too, cz his looked neat af.

For your questions

1. what is your alternative for hardcoding the response error messages? A lookup from some json?
2. From what I've seen, nothing except variable declaration is done directly in the describe block, if that is what you're suggesting.

2023-07-30 08:17 UTC, majimearun requested changes
Asked for a couple changes, and there will be some more tests you'll need to write after the edit flow (#47) is merged.

2023-07-30 08:17 UTC, majimearun commented on src/controllers/timetable/editTimetableMetadata.test.ts
> +        .orderBy("user.batch")
Does it need to be ordered

2023-07-30 08:17 UTC, majimearun commented on src/controllers/timetable/editTimetableMetadata.test.ts
> +              draft: true,
This state is invalid according to our flow, a timetable can only be private if it is a draft

2023-07-30 08:17 UTC, majimearun commented on src/controllers/timetable/editTimetableMetadata.test.ts
> +              draft: false,
Same timetable state problem

2023-07-30 08:17 UTC, majimearun commented on src/controllers/timetable/editTimetableMetadata.test.ts
> +        .orderBy("user.batch")
Again, is the order by required

2023-07-30 08:17 UTC, majimearun commented on src/controllers/timetable/editTimetableMetadata.ts
> +  const name: string = req.body.name;
Is there a reason you rearranged these lmao

2023-07-30 12:02 UTC, TheComputerM commented on src/controllers/timetable/editTimetableMetadata.ts
> +  const name: string = req.body.name;
Logically, I think it should check if the timetable exists before it checks if the user is the owner of the timetable etc.

2023-07-30 12:03 UTC, TheComputerM commented on src/controllers/timetable/editTimetableMetadata.test.ts
> +        .orderBy("user.batch")
Yeah, to test if I have updated the timetable, I store the old state and get the new state and compare them. It's would be error free if the states are in the same order.

2023-07-30 12:04 UTC, TheComputerM commented on src/controllers/timetable/editTimetableMetadata.test.ts
> +              draft: true,
Hmm, will update

2023-07-30 12:04 UTC, TheComputerM commented on src/controllers/timetable/editTimetableMetadata.test.ts
> +        .orderBy("user.batch")
See my other comment: https://github.com/crux-bphc/chronofactorem-rewrite/pull/50#discussion_r1278557568

2023-07-30 12:05 UTC, majimearun commented on src/controllers/timetable/editTimetableMetadata.test.ts
> +        .orderBy("user.batch")
yeapp okay makes sense

2023-07-31 09:36 UTC, majimearun commented
PR #47 has been merged

2024-02-07 13:13 UTC, soumitradev commented
Closing because stale, and too many changes to backend code since this PR

2024-02-07 13:13 UTC, closed without merging