Add get degrees page
crux-bphc/chronofactorem-rewrite pull request #91
Opened 2023-12-28 12:47 UTC by skoriop

2023-12-29 06:31 UTC, Anurav-Garg submitted a review, later dismissed
Other than the max year thing we discussed yesterday, LGTM. Of course, if importing from the backend works we'll want to replace this year type, as well as possibly the array containing the degrees, with their respective types from the backend; the latter might have to be extended to allow `A0` though. Still, as it is now it seems to work fine.

2023-12-29 06:31 UTC, Anurav-Garg commented on frontend/src/GetDegrees.tsx
> +  year: z.number().min(1).max(5).catch(1),
If importing the type from the backend doesn't work, set the max to 6

2023-12-29 10:11 UTC, soumitradev requested changes
Few changes regarding convention in this project

2023-12-29 10:11 UTC, soumitradev commented on frontend/src/GetDegrees.tsx
> +      const response = await fetch("/api/auth/submit", {
Remember to use `axios` instead of fetch, since that's what we're using for this project. Additionally, to show alerts in the form of toasts and navigating, please see `Home.tsx` for reference. Errors that should trigger side effects like navigation should be caught and handled in the `onError`, while ones that render toasts should use `errorComponent` to do so. Again, refer to `Home.tsx` for an example.

2023-12-29 10:11 UTC, soumitradev commented on frontend/src/GetDegrees.tsx
> +        mode: "cors",
CORS headers are no longer needed, since both will now lie on the same host

2023-12-29 10:11 UTC, soumitradev commented on frontend/src/GetDegrees.tsx
> +      <span className="fixed bottom-0 bg-slate-800 w-full text-center py-1 text-md lg:text-lg text-slate-400">
Some of these common components are now more responsive, see `Login.tsx` for an example

2023-12-29 10:11 UTC, soumitradev commented on frontend/src/GetDegrees.tsx
> +  year: z.number().min(1).max(5).catch(1),
Before merging, wait for #93 to be merged, then refactor this to import from `lib` like `Home.tsx` does in #93.

2023-12-29 10:56 UTC, soumitradev commented
As #93 is now merged you can import the type from there

2023-12-30 11:35 UTC, skoriop commented on frontend/src/GetDegrees.tsx
> +        mode: "cors",
fixed in d2717ff

2023-12-30 11:36 UTC, skoriop commented on frontend/src/GetDegrees.tsx
> +      const response = await fetch("/api/auth/submit", {
fixed in 84d6daa

2023-12-30 11:36 UTC, skoriop commented on frontend/src/GetDegrees.tsx
> +      <span className="fixed bottom-0 bg-slate-800 w-full text-center py-1 text-md lg:text-lg text-slate-400">
fixed in e729a07

2023-12-30 11:37 UTC, skoriop commented on frontend/src/GetDegrees.tsx
> +  year: z.number().min(1).max(5).catch(1),
done in 4a1b3cd

2023-12-30 12:18 UTC, soumitradev requested changes
Small alert-toast-related change and addition of 1 small comment, LGTM otherwise. However, all the colors in this will have to be edited to fit the default theme, like master now does. You can again refer to `tailwind.config.js` or #114 or `Login.tsx` on master to figure out what color related changes are required.

If you have any questions about the color thing, ping me and I'll explain. Sorry for the color thing not being communicated before when you started work on your PR, but great work nonetheless!

2023-12-30 12:18 UTC, soumitradev commented on frontend/src/GetDegrees.tsx
> +      }),
I wasn't initially sure why we need this request at all, since the user isn't created when they're on this page, but now that I think about it, we can handle a case where a user still goes to this page for whatever reason. If this request returns a 200, they should not be on this page and should be redirected to `/`.

2023-12-30 12:18 UTC, soumitradev commented on frontend/src/GetDegrees.tsx
> +      const { toast } = useToast();
define this at the top level, near `useSearch`, so you can use it in the rest of the component

2023-12-30 12:18 UTC, soumitradev commented on frontend/src/GetDegrees.tsx
> +        alert("Select your second degree!");
if you redefine the toast thing at the top level if the component this can use the toast instead

2023-12-30 12:18 UTC, soumitradev commented on frontend/src/GetDegrees.tsx
> +      alert("Select your degree!");
same here

2023-12-30 12:18 UTC, soumitradev commented on frontend/src/GetDegrees.tsx
> +      }),
I am blind and I cannot read lmao line 50 does exactly this, I'll resolve this in the final review

2023-12-30 12:18 UTC, soumitradev commented on frontend/src/GetDegrees.tsx
> +      }),
Actually ykw I'm not resolving it, since both you and I had the same confusion, just add a comment explaining why this query exists.

2023-12-30 12:26 UTC, skoriop commented on frontend/src/GetDegrees.tsx
> +      }),
Right now, after signing in through Google, users are always redirected to `/getDegrees`. If a user has already filled this out, we don't want to show it to them again. 

Since the user is actually created in the DB only after they properly fill out their degrees, we check if they exist in the DB by querying `/api/user`. If this succeeds, they have already filled this out and so we redirect them away to `/`.

If they have not filled out their degrees, they will not exist in the DB and so `/api/user` will return a 401 response. Then, we do nothing (no error toasts) and just let them fill out their degrees.

2023-12-30 13:38 UTC, soumitradev commented on frontend/src/GetDegrees.tsx
> +      }),
by this I meant add this comment to code lol

2023-12-30 13:38 UTC, soumitradev commented on frontend/src/GetDegrees.tsx
> +      const { toast } = useToast();
resolved by 2b3a735

2023-12-30 13:38 UTC, soumitradev commented on frontend/src/GetDegrees.tsx
> +      alert("Select your degree!");
resolved by 2b3a735

2023-12-30 13:38 UTC, soumitradev commented on frontend/src/GetDegrees.tsx
> +        alert("Select your second degree!");
resolved by 2b3a735

2023-12-30 13:40 UTC, soumitradev requested changes
Other than the color standardization, and the one comment you need to add to the code, it looks like we can merge it

2023-12-30 13:40 UTC, soumitradev commented on frontend/src/GetDegrees.tsx
> +      <div className="flex bg-slate-950 h-screen w-full justify-center">
now just edit the colors to reflect standard colors, like Login.tsx from master or #114 across all components

2023-12-30 13:59 UTC, skoriop commented on frontend/src/GetDegrees.tsx
> +      }),
welp ok

2023-12-30 14:47 UTC, soumitradev commented on frontend/src/GetDegrees.tsx
> +      <div className="flex bg-slate-950 h-screen w-full justify-center">
resolved by d51c6dc

2023-12-30 14:47 UTC, soumitradev approved these changes
LGTM, merging

2023-12-30 14:49 UTC, merged