Simplify, and fix ingestion --overwrite
crux-bphc/chronofactorem-rewrite pull request #92
Opened 2023-12-28 13:32 UTC by soumitradev

2023-12-29 13:35 UTC, majimearun requested changes
works for all cases except for when timetables are already created for the old ingested data.

script will need to delete those timetables (only pertaining to the old data of the same semester and not archived ones of others)

2023-12-29 15:42 UTC, soumitradev commented
Will close #98

2023-12-30 08:17 UTC, majimearun requested changes
except that one missing delete LGTM

2023-12-30 08:17 UTC, majimearun commented on backend/src/ingestJSON.ts
> +      }
sections of the course arent being deleted

2023-12-30 08:18 UTC, soumitradev commented on backend/src/ingestJSON.ts
> +      }
sections are configured to delete when their parent course is deleted anyways, so this isn't an issue

2023-12-30 08:20 UTC, soumitradev commented on backend/src/ingestJSON.ts
> +      }
see: https://github.com/crux-bphc/chronofactorem-rewrite/blob/fix-ingestion/backend/src/entity/Section.ts#L27

2023-12-30 08:20 UTC, majimearun commented on backend/src/ingestJSON.ts
> +      }
cool

2023-12-30 08:21 UTC, majimearun approved these changes
LGTM

2023-12-30 08:21 UTC, merged